<?php
    if (isset($ketQua)){
        echo '
                <p id="ketQua" style="color: #b6834c; text-align: center; font-size: 30px">Bạn đã xem đến sản phẩm cuối cùng.</p>
              ';
    }else{
//        var_dump($dataDT);
        foreach ($dataDT as $item){
            echo '
                <div class="product-list-item">
                    <div class="product-item-image">
                        <div class="hot-and-new">
                        </div>
                        <a href="http://localhost/tmobile/">
                            <img class="lazy" src="/tmobile/files/hinh-sp/'.$item['hinhAnh'].'" alt="'.$item['hinhAnh'].'">
                        </a>
                        <div class="mask">
                            <a href="">
                            <div class="mask-title">
                                <div class="icon"></div>
                                <div class="text">TMobile care</div>
                            </div>
                            <ul class="mask-list">
                                <li>BH 12 tháng nguồn, màn hình</li>
                                <li>Đổi mới 30 ngày đầu tiên</li>
                                <li>Tặng ốp lưng, dán cường lực</li>
                                <li>Hỗ trợ phần mềm trọn đời máy</li>
                            </ul>
                            </a>
                            <a class="mask-link" target="_blank" title="Xem chi tiết chính sách bảo hành tại TMobile" href="/page/chinh-sach-bao-hanh.html">Bảo hành vàng</a>
                        </div>
                    </div>
                    <div class="product-item-info">
                        <div class="product-item-left">
                            <p class="name"><a href="">'.$item['tenSP'].'</a></p>
                            <p class="price">'.number_format($item['gia'],0).' ₫</p>
                        </div>
                        <div class="product-item-right">
                            <div class="all-icon icon-promotion"></div>
                            <a href="" class="buy">Mua</a>
                        </div>
                        <div class="product-item-full-width">
                            <ul>
                                <li><p>1. Tặng: <span style="color: #ff0000;">Cường lực -</span> <span style="color: #ff0000;">Ốp lưng - Tai nghe</span> khi mua BHV</p></li>
                                <li><p>2. Giảm: <span style="color: #ff0000;">100K</span> áp dụng HSSV mua BHV tại chi nhánh<span style="color: #ff0000;"> Thái Nguyên</span></p></li>
                            </ul>
                        </div>
                    </div>
                </div>
            ';
        }
    }
?>

