<?php
    $ses = $this->session->get('acc');
?>
<div id="page-wrapper">
  	<div class="header"> 
        <h1 class="page-header">
            Bảng điều khiển<small>Xin chào <?php echo $ses['username'];?>.</small>
        </h1>
		<ol class="breadcrumb">
		  	<li><a href="#">Home</a></li>
		  	<li><a class="menu" href="#">Bảng điều khiển</a></li>
		 	<li class="active">Dữ liệu</li>
		</ol> 
							
	</div>
    <div id="page-inner">
        <div class="row">
			<div class="col-md-3 col-sm-12 col-xs-12">
				<div class="board">
                    <div class="panel panel-primary">
						<div class="number">
							<h3>
								<h3 style="text-align: center"><?php echo $soLuongDH['all'] ?></h3>
								<small>Tổng đơn hàng</small>
							</h3> 
						</div>
						<div class="icon">
						   <i class="fa fa-shopping-cart fa-5x blue"></i>
						</div>
                    </div>
				</div>
            </div>
			<div class="col-md-3 col-sm-12 col-xs-12">
				<div class="board">
                    <div class="panel panel-primary">
						<div class="number">
							<h3>
                                <h3 style="text-align: center"><?php echo $soLuongDH['dienThoai'] ?></h3>
								<small>Đơn điện thoại</small>
							</h3> 
						</div>
						<div class="icon">
						   <i class="fa fa-mobile fa-5x green"></i>
						</div>
                    </div>
				</div>
            </div>
			
			<div class="col-md-3 col-sm-12 col-xs-12">
				<div class="board">
                    <div class="panel panel-primary">
						<div class="number">
							<h3>
                                <h3 style="text-align: center"><?php echo $soLuongDH['phuKien'] ?></h3>
								<small>Đơn phụ kiện</small>
							</h3> 
						</div>
						<div class="icon">
						   <i class="fa fa-headphones fa-5x yellow"></i>
						</div>
	 
                    </div>
				</div>
            </div>
            <div class="col-md-3 col-sm-12 col-xs-12">
                <div class="board">
                    <div class="panel panel-primary">
                        <div class="number">
                            <h3>
                                <h3 style="text-align: center"><?php echo $soLuongDH['suaChua'] ?></h3>
                                <small>Sửa chữa</small>
                            </h3> 
                        </div>
                        <div class="icon">
                           <i class="fa fa-wrench fa-5x red"></i>
                        </div>
     
                    </div>
                </div>
            </div>
        </div>
	    <div class="row">
            <div class="col-sm-6 col-xs-12">
                <div class="panel panel-default chartJs">
                    <div class="panel-heading">
                        <div class="card-title">
                            <div class="title">Tổng số đơn hàng</div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <canvas id="bar-chart" class="chart"></canvas>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xs-12">
                <div class="panel panel-default chartJs">
                    <div class="panel-heading">
                        <div class="card-title">
                            <div class="title">Số đơn hàng phân theo danh mục sản phẩm</div>
                        </div>
                    </div>
                    <?php
                        $strThang ="";
                        foreach ($thongKe6Thang as $i =>$item){
                            $tongSoDon =0;
                            $soDonDT = (int)$item['dienThoai'];
                            $soDonPK = (int)$item['phuKien'];
                            $soDonSC = (int)$item['suaChua'];
                            $tongSoDon = $soDonDT + $soDonPK +$soDonSC;
                            if (strlen($strThang) <=0){
                                $strThang = $strThang.$i;
                                $strDT = $item['dienThoai'];
                                $strPK = $item['phuKien'];
                                $strSC = $item['suaChua'];
                                $strTongSoDon = "".$tongSoDon;
                            }else{
                                $strThang = $strThang.",".$i;
                                $strDT = $strDT.",".$item['dienThoai'];
                                $strPK = $strPK.",".$item['phuKien'];
                                $strSC = $strSC.",".$item['suaChua'];
                                $strTongSoDon = $strTongSoDon.",".$tongSoDon;
                            }
                        }
                    ?>
                    <input type="hidden" id="listThang" name="" value="<?php echo $strThang?>">
                    <input type="hidden" id="listDT" name="" value="<?php echo $strDT?>">
                    <input type="hidden" id="listPK" name="" value="<?php echo $strPK?>">
                    <input type="hidden" id="listSC" name="" value="<?php echo $strSC?>">
                    <input type="hidden" id="listTongSoDon" name="" value="<?php echo $strTongSoDon?>">
                    <div class="panel-body">
                        <canvas id="line-chart" class="chart"></canvas>
                    </div>
                </div>
            </div>

        </div>
		<div class="row" style="display: none">
			<div class="col-md-5">
				<div class="panel panel-default">
					<div class="panel-heading">
						Line Chart
					</div>
					<div class="panel-body">
						<div id="morris-line-chart"></div>
					</div>
				</div>
			</div>
			
			<div class="col-md-7">
				<div class="panel panel-default">
					<div class="panel-heading">
                            Bar Chart Example
                    </div>
                    <div class="panel-body">
                        <div id="morris-bar-chart"></div>
                    </div>
				</div>  
			</div>
		</div>
        <div class="row"style="display: none">
            <div class="col-md-9 col-sm-12 col-xs-12">
                <div class="panel panel-default">
					<div class="panel-heading">
					Area Chart
					</div>
					<div class="panel-body">
						<div id="morris-area-chart"></div>
					</div>
                </div>
            </div>
        </div>
        <!-- /. ROW  -->
        <div class="row">
            <div class="col-md-9 col-sm-12 col-xs-12">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        Top 10 sản phẩm bán chạy nhất
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Mã sản phẩm</th>
                                    <th>Tên sản phẩm</th>
                                    <th>Giá</th>
                                    <th>SL bán</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($top10 as $i => $item){
                                    $stt = $i+1;
                                    echo '
                                                <tr>
                                                    <td>'.$stt.'</td>
                                                    <td>'.$item['maSP'].'</td>
                                                    <td>'.$item['tenSP'].'</td>
                                                    <td>'.$item['gia'].'</td>
                                                    <td>'.$item['soLuongBan'].'</td>
                                                </tr>
                                            ';
                                }
                                ?>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-3 col-sm-12 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Tỉ lệ hoàn thành đơn hàng
                    </div>
                    <input type="hidden" id="thongKeHT" value="<?php echo $thongKeHT['thanhCong'];?>">
                    <input type="hidden" id="thongKeTB" value="<?php echo $thongKeHT['thatBai'];?>">
                    <input type="hidden" id="thongKeH" value="<?php echo $thongKeHT['huy'];?>">
                    <div class="panel-body">
                        <div id="morris-donut-chart"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
    $vitri = "1";
?>