<div id="page-wrapper">
    <div class="header">
        <h1 class="page-header">
            Sửa thông tin Banner
        </h1>
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a class="menu" href="#">Quản lý Banner</a></li>
            <li class="active">Sửa thông tin Banner</li>
        </ol>
    </div>
    <div id="page-inner">
        <form class="breadcrumb" method="post" enctype="multipart/form-data">
            <table width="100%" id="tblThemTT">
                <tr style="height: 50px">
                    <th width="150px">Hình ảnh: <i style="color: red">*</i></th>
                    <td>
                        <img height="100px" src="/tmobile/files/slideshow/<?php echo $data['hinhAnh']; ?>">
                        <br>
                        <i>* Không chọn ảnh nếu không muốn thay đổi.</i>
                        <input type="file" name="file">
                    </td>
                </tr>
                <tr style="height: 50px">
                    <th width="150px">Link: <i style="color: red">*</i></th>
                    <td><input type="text" class="form-control form-control-lg" name="link" value="<?php echo $data['link'];?>" placeholder="Nhập tên sản phẩm" aria-describedby="basic-addon1" required=""></td>
                </tr>
                <tr style="height: 50px">
                    <th width="150px">Vị trí: <i style="color: red">*</i></th>
                    <td><input type="text" class="form-control form-control-lg" name="viTri" value="<?php echo $data['viTri'];?>" placeholder="Nhập tên sản phẩm" aria-describedby="basic-addon1" required=""></td>
                </tr>
                <tr style="height: 50px">
                    <th colspan="2">
                        <input style="width: 100%;" type="submit"  id="luuThongtin" name="luuThongTin" value="Lưu thông tin">
                    </th>
                </tr>
            </table>
            <div style="color: red">
                <?php if (isset($ketQua)) echo $ketQua;?>
            </div>

        </form>
    </div>
</div>

<?php
$vitri=7;
?>
<?php $this->assets->outputJs('js'); ?>
<script type="text/javascript">
    $(document).ready(function(){
        $("#inputMau").change(function () {
            if ($("#inputMau").val().length <=0){

                var str ='<input type="file" class="" name="file" >';
                $("#addImg").empty();
                $("#addImg").append(str);
                // alert("ok");
            }else{
                var listMau = $("#inputMau").val().split(",");
                var listMauChuan=[];
                var j =0;
                for (var i=0; i<listMau.length; i++){
                    if (listMau[i].trim().length >=1){
                        listMauChuan[j] = listMau[i].trim().replace(/ /g,"_");
                        j++;
                    }
                }
                console.log(listMauChuan);

                $("#addImg").empty();
                for (var i=0; i<listMauChuan.length; i++){
                    var str ='Ảnh màu '+listMauChuan[i].trim()+'<input type="file" class="" name="file_'+listMauChuan[i].trim()+'" aria-describedby="basic-addon1" required="">';
                    $("#addImg").append(str);
                }
            }
        });
    });
</script><?php
