<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="vi" xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
 <head>
  <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="csrf-token" content="ifjzVvxBqW3vmUwZjhZM9J1XZeIcX4aQkPp8JCRy">
  <link href="http://localhost/tmobile/favicon.ico" type="image/x-icon" rel="shortcut icon" />
  <title>Điện thoại xách tay iPhone, Xiaomi, SamSung giá RẺ nhất Thái Nguyên, Bắc giang</title>
  <meta name="description" content="Điện thoại xách tay iPhone, Xiaomi, SamSung giá RẺ nhất Thái Nguyên, Bắc giang... Bảo hành 12 tháng." />
  <link rel="canonical" href="http://localhost/tmobile" />
  <meta property="og:locale" content="vi_VN" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="Điện thoại xách tay iPhone, Xiaomi, SamSung giá RẺ nhất Thái Nguyên, Bắc giang" />
  <meta property="og:description" content="Điện thoại xách tay iPhone, Xiaomi, SamSung giá RẺ nhất Thái Nguyên, Bắc giang... Bảo hành 12 tháng." />
  <meta property="og:url" content="http://localhost/tmobile" />
  <meta property="og:image" content="" />
  <?php $this->assets->outputCss('header'); ?>


  <script>
    // !function(f,b,e,v,n,t,s)
    // {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    // n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    // if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    // n.queue=[];t=b.createElement(e);t.async=!0;
    // t.src=v;s=b.getElementsByTagName(e)[0];
    // s.parentNode.insertBefore(t,s)}(window, document,'script',
    // 'https://connect.facebook.net/en_US/fbevents.js');
    // fbq('init', '2374707562641057');
    // fbq('track', 'PageView');
  </script>
  <noscript><img height="1" width="1" style="display:none"
<!--    src="https://www.facebook.com/tr?id=2374707562641057&ev=PageView&noscript=1"-->
  /></noscript>


<!--  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115880286-3"></script>-->
  <script>
    // window.dataLayer = window.dataLayer || [];
    // function gtag(){dataLayer.push(arguments);}
    // gtag('js', new Date());
    //
    // gtag('config', 'UA-115880286-3');
  </script>
 </head>
 <body>
  <div id="fb-root"></div>
  <div class="mp-pusher" id="mp-pusher">
    <nav id="mp-menu" class="mp-menu">
        <div class="mp-level">
            <ul>
                <li><a href="http://localhost/tmobile">Trang Chủ</a></li>
                <li class="mp-icon-left">
                    <a href="javascript:;">Điện thoại</a>
                    <div class="mp-level">
                        <a class="prmp" href="http://localhost/tmobile/dien-thoai">Điện thoại</a>
                        <a class="mp-back" href="javascript:;">Quay Lại</a>
                        <ul>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai?hang=Apple">Apple (iPhone)</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai?hang=SamSung">Samsung</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-oneplus">OnePlus</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-xiaomi">Xiaomi</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-oppo">OPPO (Realme)</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-lg">LG</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-asus">Asus</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-nokia">Nokia</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-google">Google</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-meizu">Meizu</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-vsmart">Vsmart</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-sony">Sony</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-sky">Sky</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-htc">HTC</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-blackberry">BlackBerry</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-lenovo">Lenovo</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-bkav">BKAV</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-nomi">Nomi</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-huawei">Huawei</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-inwatch">InWatch</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-obi-worlphone">Obi Worlphone</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-letv">LeTV</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-zte">ZTE (Nubia)</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-vivo">Vivo</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-leeco">LeEco</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-oukitel">Oukitel</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-w-mobile">W-Mobile</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-blackview">BlackView</a></li>
                            <li class=""><a href="http://localhost/tmobile/dien-thoai-smartisan">Smartisan</a></li>
                        </ul>
                    </div>
                </li>
                <li class="mp-icon-left">
                    <a href="javascript:;">Tablet</a>
                    <div class="mp-level">
                        <a class="prmp" href="http://localhost/tmobile/may-tinh-bang">Tablet</a>
                        <a class="mp-back" href="javascript:;">Quay Lại</a>
                        <ul>
                            <li><a href="http://localhost/tmobile/may-tinh-bang-ipad">iPad</a></li>
                            <li><a href="http://localhost/tmobile/may-tinh-bang-samsung-galaxy-tab">Samsung Galaxy Tab</a></li>
                        </ul>
                    </div>
                </li>
                <li class="mp-icon-left">
                    <a href="javascript:;">Phụ kiện</a>
                    <div class="mp-level">
                        <a class="prmp" href="http://localhost/tmobile/phu-kien">Phụ kiện</a>
                        <a class="mp-back" href="javascript:;">Quay Lại</a>
                        <ul>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-tai-nghe">Loa - Tai nghe</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-dong-ho-thong-minh">Đồng hồ thông minh</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-pin-sac-du-phong">Pin, Sạc dự phòng</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-iphone">Phụ kiện iPhone</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-do-choi-cong-nghe">Đồ chơi công nghệ</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-xiaomi">Phụ kiện Xiaomi</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-may-loc-khong-khi">Máy lọc không khí</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-sony">Phụ kiện Sony</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-samsung">Phụ kiện Samsung</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-lg">Phụ kiện LG</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-lenovo">Phụ kiện Lenovo</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-ipad">Phụ kiện iPad</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-meizu">Phụ kiện Meizu</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-blackberry">Phụ kiện BlackBerry</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-phu-kien-oppo">Phụ kiện Oppo</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/phu-kien-phu-kien-khac">Phụ kiện khác</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mp-icon-left">
                    <a href="javascript:;">Sửa chữa</a>
                    <div class="mp-level">
                        <a class="prmp" href="http://localhost/tmobile/sua-chua-dien-thoai">Sửa chữa</a>
                        <a class="mp-back" href="javascript:;">Quay Lại</a>
                        <ul>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-iphone">iPhone</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-dien-thoai-xiaomi">Xiaomi</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-samsung">Samsung</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-oppo">Oppo</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-realme">Realme</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-honor">Honor</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-ipad">iPad</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-sony">Sony</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-htc">HTC</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-lg">LG</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-asus">Asus</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-blackberry">Blackberry</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-Vivo">Vivo</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-mobiistar">Mobiistar</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-huawei">Huawei</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-sim-ghep-cho-iphone">Sim Ghép iPhone</a>
                            </li>
                            <li>
                                <a href="http://localhost/tmobile/sua-chua-hang-khac">Hãng khác</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mp-icon-left">
                    <a href="javascript:;">Tin tức</a>
                    <div class="mp-level">
                        <a class="prmp" href="http://localhost/tmobile/tin-tuc">Tin tức</a>
                        <a class="mp-back" href="javascript:;">Quay Lại </a>
                        <ul>
                            <li>
                            <a href="http://localhost/tmobile/tin-tuc-khuyen-mai">Tin khuyến mại</a>
                            </li>
                            <li>
                            <a href="http://localhost/tmobile/tin-tuc-tu-van-chon-mua">Tư vấn chọn mua</a>
                            </li>
                            <li>
                            <a href="http://localhost/tmobile/tin-tuc-goc-ky-thuat">Góc kỹ thuật</a>
                            </li>
                            <li>
                            <a href="http://localhost/tmobile/tin-tuc-cong-nghe">Tin công nghệ</a>
                            </li>
                            <li>
                            <a href="http://localhost/tmobile/tin-tuc-tuyen-dung">Tuyển dụng</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class=""><a href="http://localhost/tmobile/lien-he">Liên hệ</a></li>
                <li class=""><a target="" href="https://forum.mobilecity.vn/">Diễn đàn</a></li>
            </ul>
        </div>
    </nav>
    <header>

        <div class="header-main">
            <div class="container" style="overflow: inherit;">
            <div class="logo">
            <button class="hiddenMenu" id="hiddenMenu"><i class="fa fa-bars"></i></button>
            <a href="http://localhost/tmobile/">
            <div class="icon-logo">
<!--                 <img src="img/logo_tmobile.png" alt="Image" >-->
                <i class="fa fa-mobile" aria-hidden="true"></i>
                <h>TMobile.</h>
            </div>
            </a>
            <button class="hiddenSearch" id="mb-search-btn"><i class="fa fa-search"></i></button>
            <div class="mb-search">
            <div class="mb-search-form">
            <form action="http://localhost/tmobile/tim-kiem" method="GET">
            <button type="button" class="btn-close-mb-search"><i></i></button>
            <input type="text" name="keyword" id="keyword_mobile" autocomplete="off" placeholder="Tìm kiếm sản phẩm ...">
            <button type="submit" class="btn-search-mb"><i></i></button>
            </form>
            </div>
            <div class="suggest-search-mb">
            <ul class="suggest-search-list-mb"></ul>
            </div>
            </div>
            </div>
            <div class="search">
            <form action="http://localhost/tmobile/tim-kiem" method="get">
            <input type="text" name="keyword" id="keyword" autocomplete="off" placeholder="Tìm kiếm sản phẩm ...">
            <button type="submit" class="btn-search">
            <div class="all-icon icon-search"></div>
            </button>
            </form>
            <div class="suggest-search">
            <ul class="suggest-search-list"></ul>
            </div>
            </div>
            <nav class="menu">
            <ul>
            <li><a href="http://localhost/tmobile/dien-thoai">
            <div class="all-icon icon-phone"></div>
            Điện thoại</a>
            <div class="sub-menu" id="box-menu">
            <div class="left-menu">
            <div class="title-menu"><p>Hãng sản xuất</p>
            <ul>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Apple">Apple (iPhone)</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=SamSung">Samsung</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=OnePlus">OnePlus</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Xiaomi">Xiaomi</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Oppo">OPPO (Realme)</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=LG">LG</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Asus">Asus</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Nokia">Nokia</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Google">Google</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Meizu">Meizu</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Vsmart">Vsmart</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Sony">Sony</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Sky">Sky</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=HTC">HTC</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=BlackBerry">BlackBerry</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Lenovo">Lenovo</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=BKAV">BKAV</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Nomi">Nomi</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Huawei">Huawei</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=InWatch">InWatch</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Obi_Worlphone">Obi Worlphone</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=LeTV">LeTV</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=ZTE">ZTE (Nubia)</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Vivo">Vivo</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=LeEco">LeEco</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Oukitel">Oukitel</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=W-Mobile">W-Mobile</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=BlackView">BlackView</a>
            </li>
            <li><a href="http://localhost/tmobile/dien-thoai?hang=Smartisan">Smartisan</a>
            </li>
            </ul>
            </div>
            </div>
            <div class="right-menu">
            <div class="title-menu"><p>Mức giá</p></div>
            <ul>
            <li>
            <a href="http://localhost/tmobile/dien-thoai?phanKhuc<2000000">Dưới
            2 triệu</a></li>
            <li>
            <a href="http://localhost/tmobile/dien-thoai?phanKhuc>2000000_AND_phanKhuc<4000000">Từ 2 - 4 triệu</a></li>
            <li>
            <a href="http://localhost/tmobile/dien-thoai?phanKhuc>4000000_AND_phanKhuc<6000000">Từ 4 - 6 triệu</a></li>
            <li>
            <a href="http://localhost/tmobile/dien-thoai?phanKhuc>6000000_AND_phanKhuc<8000000">Từ 6- 8 triệu</a></li>
            <li>
            <a href="http://localhost/tmobile/dien-thoai?phanKhuc>8000000_AND_phanKhuc<10000000">Từ 8 - 10 triệu</a></li>
            <li>
            <a href="http://localhost/tmobile/dien-thoai?phanKhuc>10000000">Trên 10 triệu</a></li>
            </ul>
            </div>
            <div class="bottom-menu">
            </div>
            </li>
            <li><a href="http://localhost/tmobile/may-tinh-bang">
            <div class="all-icon icon-tablet"></div>
            Tablet</a>
            <div class="sub-menu" id="box-menu">
            <div class="left-menu">
            <div class="title-menu"><p>Hãng sản xuất</p>
            <ul>
            <li><a href="http://localhost/tmobile/may-tinh-bang?hang_LIKE_'%Apple%'">Apple (iPad)</a>
            </li>
            <li><a href="http://localhost/tmobile/may-tinh-bang?hang_LIKE_'%SamSung%'">Samsung</a>
            </li>
            </ul>
            </div>
            </div>
            <div class="right-menu">
            <div class="title-menu"><p>Mức giá</p></div>
                <ul>
                    <li>
                        <a href="http://localhost/tmobile/may-tinh-bang?phanKhuc<2000000">Dưới
                            2 triệu</a></li>
                    <li>
                        <a href="http://localhost/tmobile/may-tinh-bang?phanKhuc>2000000_AND_phanKhuc<4000000">Từ 2 - 4 triệu</a></li>
                    <li>
                        <a href="http://localhost/tmobile/may-tinh-bang?phanKhuc>4000000_AND_phanKhuc<6000000">Từ 4 - 6 triệu</a></li>
                    <li>
                        <a href="http://localhost/tmobile/may-tinh-bang?phanKhuc>6000000_AND_phanKhuc<8000000">Từ 6- 8 triệu</a></li>
                    <li>
                        <a href="http://localhost/tmobile/may-tinh-bang?phanKhuc>8000000_AND_phanKhuc<10000000">Từ 8 - 10 triệu</a></li>
                    <li>
                        <a href="http://localhost/tmobile/may-tinh-bang?phanKhuc>10000000">Trên 10 triệu</a></li>
                </ul>
            </div>
            <div class="bottom-menu">
            </div>
            </li>
            <li><a href="http://localhost/tmobile/phu-kien">
            <div class="all-icon icon-dependency"></div>
            Phụ kiện</a>
            <div class="sub-menu-type-2" id="box-menu">
            <div class="title-menu"><p>Phân loại phụ kiện</p>
            <ul>
            <li>
            <a href="http://localhost/tmobile/phu-kien?loai_LIKE_'%tai-nghe%'">Loa - Tai nghe</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?loai_LIKE_'%dong-ho-thong-minh%'">Đồng hồ thông minh</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?loai_LIKE_'%sac-du-phong%'">Pin, Sạc dự phòng</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?hang_LIKE_'%Apple%'">Phụ kiện iPhone</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?loai_LIKE_'%ho-tro-gamer%'">Hỗ trợ gamer</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?hang_LIKE_'%Xiaomi%'">Phụ kiện Xiaomi</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?hang_LIKE_'%Sony%'">Phụ kiện Sony</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?hang_LIKE_'%SamSung%'">Phụ kiện Samsung</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?hang_LIKE_'%LG%'">Phụ kiện LG</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?hang_LIKE_'%Lenovo%'">Phụ kiện Lenovo</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien?hang_LIKE_'%Oppo%'">Phụ kiện Oppo</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/phu-kien">Phụ kiện khác</a>
            </li>
            </ul>
            </div>
            </div>
            </li>
            <li><a href="http://localhost/tmobile/sua-chua-dien-thoai">
            <div class="all-icon icon-repair"></div>
            Sửa chữa</a>
            <div class="sub-menu-type-2" id="box-menu">
            <div class="title-menu"><p>Phân loại</p>
            <ul>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Apple%'">Apple (iPhone)</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Xiaomi%'">Xiaomi</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Samsung%'">Samsung</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Oppo%'">Oppo</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Realme%'">Realme</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Honor%'">Honor</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%iPad%'">iPad</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Sony%'">Sony</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%HTC%'">HTC</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%LG%'">LG</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Asus%'">Asus</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Blackberry%'">Blackberry</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Vivo%'">Vivo</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Mobiistar%'">Mobiistar</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai?hang_LIKE_'%Huawei%'">Huawei</a>
            </li>
            <li>
            <a href="http://localhost/tmobile/sua-chua-dien-thoai">Hãng khác</a>
            </li>
            </ul>
            </div>
            </div>
            </li>
            <li><a href="http://localhost/tmobile/tin-tuc">
            <div class="all-icon icon-endow"></div>
            Tin tức</a></li>
            </ul>
            </nav>
            </div>
        </div>
    </header>

    <?php $this->assets->outputJs('footer'); ?>

    <section class="container">
        <?php echo $this->getContent(); ?>
    </section>
    <footer>
        <div class="container">
            <div class="footer-top">
                <div class="footer-top-item">
                    <div class="title">
                        <div class="all-icon icon-location"></div>
                        Hệ thống cửa hàng
                    </div>
                    <div class="footer-top-content">
                        <div class="address-group">
                            <div class="address-group-title">Bắc Giang</div>
                            <div class="address-group-main">
                                <div class="address-group-item">
                                    <address>Xóm quất, Hợp Đức, Tân Yên<a href="" target="_blank">Xem bản đồ</a></address>
                                    <p>Điện thoại: <a href="tel:0971206688">097.120.6688</a>
                                        -
                                        <a href="tel:0969120120">0969.120.120</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="address-group">
                            <div class="address-group-title">Thái Nguyên</div>
                            <div class="address-group-main">
                                <div class="address-group-item">
                                    <address>123 Trần Quang Khải, Q.1<a href="" target="_blank">Xem bản đồ</a></address>
                                    <p>Điện thoại: <a href="tel:0965123123">0965.123.123</a>
                                        -
                                        <a href="tel:0969520520">0969.520.520</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-top-item">
                    <div class="title">
                        <div class="all-icon icon-policy"></div>
                        quy định - chính sách
                    </div>
                    <div class="footer-top-content">
                        <ul class="footer-list">
                            <li><a href="http://localhost/tmobile/page/chinh-sach-bao-hanh.html" target="_blank">Chính sách bảo hành</a></li>
                            <li><a href="http://localhost/tmobile/page/chinh-sach-van-chuyen.html" target="_blank">Chính sách vận chuyển</a></li>
                            <li><a href="http://localhost/tmobile/page/chinh-sach-doi-tra-hang.html" target="_blank">Chính sách đổi trả hàng</a></li>
                            <li><a href="http://localhost/tmobile/page/chinh-sach-bao-mat-thong-tin.html" target="_blank">Chính sách bảo mật thông tin</a></li>
                            <li><a href="http://localhost/tmobile/page/huong-dan-thanh-toan.html" target="_blank">Hướng dẫn thanh toán</a></li>
                            <li><a href="http://localhost/tmobile/page/huong-dan-mua-hang-online.html" target="_blank">Hướng dẫn mua hàng Online</a></li>
                            <li><a href="http://localhost/tmobile/page/dich-vu-van-chuyen-hang-thu-tien-tan-noi-mobilecity.html" target="_blank">Dịch vụ Ship COD Toàn quốc</a></li>
                            <li><a href="http://localhost/tmobile/page/chinh-sach-dai-ly.html" target="_blank">Chính sách đại lý linh, phụ kiện</a></li>
                        </ul>
                    </div>
                </div>
                <div class="footer-top-item">
                    <div class="title">
                        <div class="all-icon icon-email"></div>
                        Đăng ký nhận bảng tin
                    </div>
                    <div class="footer-top-content">
                        <div class="subscribe-form">
                            <input type="text" id="subscribe-email" placeholder="Nhập email của bạn...">
                            <button id="subscribe-btn" class="btn_nhan">Gửi</button>
                        </div>
                    </div>
                    <div class="title">
                        <div class="all-icon icon-connect"></div>
                        Liên kết
                    </div>
                    <div class="footer-top-content">
                        <div class="connect-content">
                            <div class="connect-content-item">
                                <div class="all-icon icon-facebook"></div>
                                <a target="_blank" href="https://www.facebook.com/">Facebook</a>
                            </div>
                            <div class="connect-content-item">
                                <div class="all-icon icon-youtube"></div>
                                <a target="_blank" href="https://www.youtube.com/">Youtube</a>
                            </div>
                            <div class="connect-content-item">
                                <div class="all-icon icon-forum-2"></div>
                                <a target="_blank" href="">Diễn đàn hỗ trợ</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-top-item">
                    <div class="footer-top-content">
                        <div class="icon-footer">
                            <div class="all-icon icon-notification"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="footer-bottom-item">
                    <p>© 2020. TMobile hệ thống bán lẻ điện thoại di động.</p>
                </div>
                <div class="footer-bottom-item">
                    <p>Bạn có thể thanh toán với</p>
                    <div class="all-icon icon-bank"></div>
                </div>
                <div class="footer-bottom-item">
                    <p>Tư vấn và phát triển bởi: <a href="https://www.facebook.com/thoi.nguyen2498" rel="nofollow" target="_blank">ThoiNV</a></p>
                </div>
            </div>
        </div>
    </footer>
  </div>

  <span id="gototop"></span>
  <div id="loading_box">
    <div id="loading_image"></div>
  </div>
  <div class="alert_message"></div>

<!--  <script>-->
<!--      function suggest_search_template(element) {-->
<!--          return `-->
<!--                  <li><a href="${element.url}">-->
<!--                      <div class="img">-->
<!--                          <img src="${element.image}" alt="${element.name}">-->
<!--                      </div>-->
<!--                      <div class="info">-->
<!--                          <h4 class="name">${element.name}</h4>-->
<!--                          <p class="price">${element.price}</p>-->
<!--                      </div>-->
<!--                  </a></li>-->
<!--              `;-->
<!--      }-->
<!--      $(document).ready(function () {-->
<!--          // search ajax bản PC và mobile-->
<!--          // PC-->
<!--          $('#keyword').on('keyup', function () {-->
<!--              var vcheck = [3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29];-->
<!--              var keyword = $(this).val();-->
<!--              data = {'keyword': keyword}-->
<!--              if (jQuery.inArray(keyword.length, vcheck) != '-1') {-->
<!--                  loadAjax('http://localhost/tmobile/ajax/search', data, {-->
<!--                      beforeSend: function () {-->
<!--                      },-->
<!--                      success: function (result) {-->
<!--                          if (result.status == 1) {-->
<!--                              $('.suggest-search-list').empty();-->
<!--                              result.data.forEach(function (element, index) {-->
<!--                                  suggest_template = suggest_search_template(element);-->
<!--                                  $('.suggest-search-list').append(suggest_template);-->
<!--                              });-->
<!--                              $('.suggest-search').css('display', 'block');-->
<!--                          } else {-->
<!--                              $('.suggest-search').css('display', 'none');-->
<!--                          }-->
<!--                      }-->
<!--                  });-->
<!--              } else {-->
<!--                  $('.suggest-search').css('display', 'none');-->
<!--              }-->
<!--          });-->
<!--          // mobile-->
<!--          $('#keyword_mobile').on('keyup', function () {-->
<!--              var vcheck = [3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29];-->
<!--              var keyword = $(this).val();-->
<!--              data = {'keyword': keyword}-->
<!--              if (jQuery.inArray(keyword.length, vcheck) != '-1') {-->
<!--                  loadAjax('http://localhost/tmobile/ajax/search', data, {-->
<!--                      beforeSend: function () {-->
<!--                      },-->
<!--                      success: function (result) {-->
<!--                          if (result.status == 1) {-->
<!--                              $('.suggest-search-list-mb').empty();-->
<!--                              result.data.forEach(function (element, index) {-->
<!--                                  suggest_template = suggest_search_template(element);-->
<!--                                  $('.suggest-search-list-mb').append(suggest_template);-->
<!--                              });-->
<!--                              $('.suggest-search-mb').css('display', 'block');-->
<!--                          } else {-->
<!--                              $('.suggest-search-mb').css('display', 'none');-->
<!--                          }-->
<!--                      }-->
<!--                  });-->
<!--              } else {-->
<!--                  $('.suggest-search-mb').css('display', 'none');-->
<!--              }-->
<!--          });-->
<!--      });-->
<!--  </script>-->
<!---->
<!--  <script type="text/javascript">-->
<!--      $(document).ready(function() {-->
<!--          $.ajaxSetup({-->
<!--              headers: {-->
<!--                  'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')-->
<!--              }-->
<!--          });-->
<!--          var page_phones = 1;-->
<!--          var page_fits = 1;-->
<!--          var page_services = 1;-->
<!--          $(".product-box").on('click', '.more', function(event) {-->
<!--              event.preventDefault();-->
<!--              var that = $(this).closest('.product-box');-->
<!--              var count = $(this).data('count');-->
<!--              var type = $(this).data('type');-->
<!---->
<!--              var location = $(this).data('location');-->
<!--              switch (type) {-->
<!--                  case 'phones':-->
<!--                      page_phones++;-->
<!--                      $.ajax({-->
<!--                          type: "POST",-->
<!--                          url: "http://localhost/tmobile/home_view_more_product",-->
<!--                          data: {count:count,page:page_phones,type:type,location:location},-->
<!--                          dataType: "JSON",-->
<!---->
<!--                          success: function (response) {-->
<!--                              console.log("zz");-->
<!--                              if(response.list_item == ""){-->
<!--                                  that.find('.viewmore').css('display','none');-->
<!--                              }-->
<!--                              $.each(response.list_item, function (key, value) {-->
<!--                                  that.find('.product-list').append(value);-->
<!--                              });-->
<!--                              $(function() {-->
<!--                                  $("img[src='http://localhost/tmobile/public/assets/img/load_video.svg']").lazyload({-->
<!--                                      effect : "fadeIn",-->
<!--                                      failure_limit: 10,-->
<!--                                  });-->
<!--                              });-->
<!--                          }-->
<!--                      });-->
<!--                      break;-->
<!--                  case 'fits':-->
<!--                      page_fits++;-->
<!--                      $.ajax({-->
<!--                          type: "POST",-->
<!--                          url: "http://localhost/tmobile/home_view_more_product",-->
<!--                          data: {count:count,page:page_fits,type:type,location:location},-->
<!--                          dataType: "JSON",-->
<!---->
<!--                          success: function (response) {-->
<!--                              console.log("zz");-->
<!--                              if(response.list_item == ""){-->
<!--                                  that.find('.viewmore').css('display','none');-->
<!--                              }-->
<!--                              $.each(response.list_item, function (key, value) {-->
<!--                                  that.find('.product-list').append(value);-->
<!--                              });-->
<!--                              $(function() {-->
<!--                                  $("img[src='http://localhost/tmobile/public/assets/img/load_video.svg']").lazyload({-->
<!--                                      effect : "fadeIn",-->
<!--                                      failure_limit: 10,-->
<!--                                  });-->
<!--                              });-->
<!--                          }-->
<!--                      });-->
<!--                      break;-->
<!--                  case 'services':-->
<!--                      page_services++;-->
<!--                      $.ajax({-->
<!--                          type: "POST",-->
<!--                          url: "http://localhost/tmobile/home_view_more_product",-->
<!--                          data: {count:count,page:page_services,type:type,location:location},-->
<!--                          dataType: "JSON",-->
<!---->
<!--                          success: function (response) {-->
<!--                              console.log("zz");-->
<!--                              if(response.list_item == ""){-->
<!--                                  that.find('.viewmore').css('display','none');-->
<!--                              }-->
<!--                              $.each(response.list_item, function (key, value) {-->
<!--                                  that.find('.product-list').append(value);-->
<!--                              });-->
<!--                              $(function() {-->
<!--                                  $("img[src='http://localhost/tmobile/public/assets/img/load_video.svg']").lazyload({-->
<!--                                      effect : "fadeIn",-->
<!--                                      failure_limit: 10,-->
<!--                                  });-->
<!--                              });-->
<!--                          }-->
<!--                      });-->
<!--                      break;-->
<!--              }-->
<!---->
<!---->
<!--              // page++;-->
<!--              // $.ajax({-->
<!--     //              type: "POST",-->
<!--     //              url: "",-->
<!--     //              data: {count:count,page:page,type:type},-->
<!--     //              dataType: "JSON",-->
<!--     //              beforeSend:function(){-->
<!--        //           },-->
<!--     //              success: function (response) {-->
<!--     //               console.log(response);-->
<!--     //               if(response.list_item == ""){-->
<!--     //                   that.find('.viewmore').css('display','none');-->
<!--     //               }-->
<!--              //      $.each(response.list_item, function (key, value) {-->
<!--     //                      that.find('.product-list').append(value);-->
<!--     //                  });-->
<!--     //              }-->
<!--     //          });-->
<!---->
<!--          });-->
<!--      });-->
<!--  </script>-->
  <a class="mobilecity-messenger" href="https://m.me/thoi.nguyen2498" target="_blank"></a>
  
 </body>
</html>