 <?php $this->assets->outputCss('cssdt'); ?>
<div class="breadcrumb">
    <ul itemscope itemtype="http://schema.org/BreadcrumbList">
        <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            <a itemprop="item" href="https://mobilecity.vn"><span itemprop="name">Trang chủ</span></a>
            <meta itemprop="position" content="1" />
        </li>
        <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            <a itemprop="item" href="https://mobilecity.vn/dien-thoai"><span itemprop="name">Điện thoại di động</span></a>
            <meta itemprop="position" content="2" />
        </li>
    </ul>
</div>
<div class="intro-category">
    <h1 class="intro-category-title">Điện thoại</h1>
</div>
    <section class="product-box">
        <div class="product-fillter-box">
            <ul>
                <li>Tìm theo</li>
                <li><a href="javascript:;" class="filterSelect">Mức giá</a>
                    <ul class="dropdown-filter">
                        <li class="checked"><a href="">Tất cả</a></li>
                        <li><a href="/dien-thoai?price=max_1m">Dưới 1 triệu</a></li>
                        <li><a href="/dien-thoai?price=max_2m">Dưới 2 triệu</a></li>
                        <li><a href="/dien-thoai?price=max_3m">Dưới 3 triệu</a></li>
                        <li><a href="/dien-thoai?price=max_5m">Dưới 5 triệu</a></li>
                        <li><a href="/dien-thoai?price=max_7m">Dưới 7 triệu</a></li>
                        <li><a href="/dien-thoai?price=max_10m">Dưới 10 triệu</a></li>
                        <li><a href="/dien-thoai?price=min_10m">Trên 10 triệu</a></li>
                    </ul>
                </li>
                <li><a href="javascript:;">Hãng sản xuất</a>
                    <ul class="dropdown-filter filter-column">
                        <li class="checked"><a href="">Tất cả</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-tivi-xiaomi-1">Tivi Xiaomi</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-apple">Apple (iPhone) - Quốc tế</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-iphone-lock">Apple (iPhone) - Lock</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-samsung">Samsung</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-oneplus">OnePlus</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-xiaomi">Xiaomi</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-oppo">OPPO (Realme)</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-lg">LG</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-asus">Asus</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-nokia">Nokia</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-google">Google</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-meizu">Meizu</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-vsmart">Vsmart</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-sony">Sony</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-sky">Sky</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-htc">HTC</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-blackberry">BlackBerry</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-lenovo">Lenovo</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-bkav">BKAV</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-nomi">Nomi</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-huawei">Huawei</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-inwatch">InWatch</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-obi-worlphone">Obi Worlphone</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-letv">LeTV</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-zte">ZTE (Nubia)</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-vivo">Vivo</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-leeco">LeEco</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-oukitel">Oukitel</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-w-mobile">W-Mobile</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-blackview">BlackView</a></li>
                        <li><a href="https://mobilecity.vn/dien-thoai-smartisan">Smartisan</a></li>
                    </ul>
                </li>
                <li><a href="javascript:;">Hệ điều hành</a>
                    <ul class="dropdown-filter">
                        <li class="checked"><a href="">Tất cả</a></li>
                        <li><a href="/dien-thoai?os=android">Android</a></li>
                        <li><a href="/dien-thoai?os=ios">iOS (iPhone)</a></li>
                        <li><a href="/dien-thoai?os=windows">Window Phone</a></li>
                        <li><a href="/dien-thoai?os=other">HĐH Khác</a></li>
                    </ul>
                </li>
                <li><a href="javascript:;">Màn hình</a>
                    <ul class="dropdown-filter">
                        <li class="checked"><a href="">Tất cả</a></li>
                        <li><a href="/dien-thoai?display=duoi-3">Dưới 3"</a></li>
                        <li><a href="/dien-thoai?display=khoang-3">Khoảng 3"</a></li>
                        <li><a href="/dien-thoai?display=khoang-4">Khoảng 4"</a></li>
                        <li><a href="/dien-thoai?display=khoang-5">Khoảng 5"</a></li>
                        <li><a href="/dien-thoai?display=khoang-6">Khoảng 6</a></li>
                    </ul>
                </li>
                <li><a href="javascript:;">Tính năng</a>
                    <ul class="dropdown-filter">
                        <li class="checked"><a href="">Tất cả</a></li>
                        <li><a href="/dien-thoai?feature=bang-tan-3g-4g">Băng tần 3G, 4G</a></li>
                        <li><a href="/dien-thoai?feature=2-sim-2-song">2 Sim 2 Sóng</a></li>
                        <li><a href="/dien-thoai?feature=smartphone">SmartPhone</a></li>
                        <li><a href="/dien-thoai?feature=wifi">Wifi</a></li>
                        <li><a href="/dien-thoai?feature=cam-ung">Cảm ứng</a></li>
                    </ul>
                </li>
                <li><a href="javascript:;">Sắp xếp theo giá</a>
                    <ul class="dropdown-filter">
                    <li class="checked"><a href="">Tất cả</a></li>
                    <li><a href="/dien-thoai?order=thap-den-cao">Giá thấp đến cao</a></li>
                    <li><a href="/dien-thoai?order=cao-den-thap">Giá cao đến thấp</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="product-list">
            <div class="product-list-item">
                <div class="product-item-image">
                    <div class="hot-and-new">
                    </div>
                    <a href="https://mobilecity.vn/lenovo/lenovo-k5.html">
                        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2019/03/lenovo-k5-small.jpg" alt="lenovo-k5">
                    </a>
                    <div class="mask">
                        <a href="https://mobilecity.vn/lenovo/lenovo-k5.html">
                            <div class="mask-title">
                                <div class="icon"></div>
                                <div class="text">MobileCity Care</div>
                            </div>
                            <ul class="mask-list">
                                <li>BH 12 tháng nguồn, màn hình</li>
                                <li>Đổi mới 30 ngày đầu tiên</li>
                                <li>Tặng ốp lưng, dán cường lực</li>
                                <li>Hỗ trợ phần mềm trọn đời máy</li>
                            </ul>
                        </a>
                        <a class="mask-link" target="_blank" title="Xem chi tiết chính sách bảo hành tại MobileCity" href="/page/chinh-sach-bao-hanh.html">Bảo hành vàng</a>
                    </div>
                </div>
                <div class="product-item-info">
                    <div class="product-item-left">
                        <p class="name"><a href="https://mobilecity.vn/lenovo/lenovo-k5.html">Lenovo K5 (RAM 3GB, Có Vân Tay)</a></p>
                        <p class="price">1.950.000 ₫</p>
                    </div>
                    <div class="product-item-right">
                        <div class="all-icon icon-promotion"></div>
                        <a href="https://mobilecity.vn/lenovo/lenovo-k5.html" class="buy">Mua</a>
                    </div>
                    <div class="product-item-full-width">
                        <ul>
                            <li><p>1. Tặng: <span style="color: #ff0000;">Cường lực -</span> <span style="color: #ff0000;">Ốp lưng - Tai nghe</span> khi mua BHV</p></li>
                            <li><p>2. Giảm: <span style="color: #ff0000;">100K</span> áp dụng HSSV mua BHV tại <span style="color: #ff0000;">398 Cầu Giấy</span></p></li>
                            <li><p>3. Mua: Dán cường lực 5D chỉ <span style="color: #ff0000;">99K</span></p></li>
                            <li><p>4. Giảm 100K khi mua BHV và đặt hàng tại: <a title="https://goo.gl/PH4Pw9" href="https://www.messenger.com/t/dienthoaixiaomigiare.vn">Đây</a></p></li>
                            <li><p>5. Cam kết bán iPhone RẺ nhất VN: <a title="iPhone giá RẺ" href="https://goo.gl/6xKTMo">CLICK</a></p></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="view-ajax-more">
        <img src="https://mobilecity.vn/public/assets/img/load_video.svg" alt="load_video">
        </div>
        <div class="viewmore">
        <a class="more" href="javascript:;" id="product_view_more" data-get_price="" data-get_os="" data-get_display="" data-get_feature="" data-location="1" data-get_order="" data-count="20">Xem thêm điện thoại</a>
        </div>
    </section>
    <div class="intro-category">
</div>