<?php $this->assets->outputCss('cssmtb'); ?>
<div class="breadcrumb">
    <ul itemscope itemtype="http://schema.org/BreadcrumbList">
        <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            <a itemprop="item" href="https://mobilecity.vn"><span itemprop="name">Trang chủ</span></a>
            <meta itemprop="position" content="1" />
        </li>
        <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            <a itemprop="item" href="https://mobilecity.vn/may-tinh-bang"><span itemprop="name">Máy tính bảng</span></a>
            <meta itemprop="position" content="2" />
        </li>
    </ul>
</div>
<div class="intro-category">
    <h1 class="intro-category-title">Máy tính bảng</h1>
</div>
<section class="product-box">
    <div class="product-fillter-box">
        <ul>
            <li>Tìm theo</li>
            <li><a href="javascript:;" class="filterSelect">Mức giá</a>
                <ul class="dropdown-filter">
                    <li class="checked"><a href="">Tất cả</a></li>
                    <li><a href="/may-tinh-bang?price=max_1m">Dưới 1 triệu</a></li>
                    <li><a href="/may-tinh-bang?price=max_2m">Dưới 2 triệu</a></li>
                    <li><a href="/may-tinh-bang?price=max_3m">Dưới 3 triệu</a></li>
                    <li><a href="/may-tinh-bang?price=max_5m">Dưới 5 triệu</a></li>
                    <li><a href="/may-tinh-bang?price=max_7m">Dưới 7 triệu</a></li>
                    <li><a href="/may-tinh-bang?price=max_10m">Dưới 10 triệu</a></li>
                    <li><a href="/may-tinh-bang?price=min_10m">Trên 10 triệu</a></li>
                </ul>
            </li>
            <li><a href="javascript:;">Hãng sản xuất</a>
                <ul class="dropdown-filter filter-column">
                    <li class="checked"><a href="">Tất cả</a></li>
                    <li><a href="https://mobilecity.vn/may-tinh-bang-ipad">iPad</a></li>
                    <li><a href="https://mobilecity.vn/may-tinh-bang-samsung-galaxy-tab">Samsung Galaxy Tab</a></li>
                </ul>
            </li>
            <li><a href="javascript:;">Hệ điều hành</a>
                <ul class="dropdown-filter">
                    <li class="checked"><a href="">Tất cả</a></li>
                    <li><a href="/may-tinh-bang?os=android">Android</a></li>
                    <li><a href="/may-tinh-bang?os=ios">iOS (iPhone)</a></li>
                    <li><a href="/may-tinh-bang?os=windows">Window Phone</a></li>
                    <li><a href="/may-tinh-bang?os=other">HĐH Khác</a></li>
                </ul>
            </li>
            <li><a href="javascript:;">Màn hình</a>
                <ul class="dropdown-filter">
                    <li class="checked"><a href="">Tất cả</a></li>
                    <li><a href="/may-tinh-bang?display=duoi-7">Dưới 7"</a></li>
                    <li><a href="/may-tinh-bang?display=khoang-7">Khoảng 7"</a></li>
                    <li><a href="/may-tinh-bang?display=khoang-8">Khoảng 8"</a></li>
                    <li><a href="/may-tinh-bang?display=khoang-10">Khoảng 10"</a></li>
                    <li><a href="/may-tinh-bang?display=khoang-12">Khoảng 12"</a></li>
                </ul>
            </li>
            <li><a href="javascript:;">Tính năng</a>
                <ul class="dropdown-filter">
                    <li class="checked"><a href="">Tất cả</a></li>
                    <li><a href="/may-tinh-bang?feature=bang-tan-3g-4g">Băng tần 3G, 4G</a></li>
                    <li><a href="/may-tinh-bang?feature=2-sim-2-song">2 Sim 2 Sóng</a></li>
                    <li><a href="/may-tinh-bang?feature=smartphone">SmartPhone</a></li>
                    <li><a href="/may-tinh-bang?feature=wifi">Wifi</a></li>
                    <li><a href="/may-tinh-bang?feature=cam-ung">Cảm ứng</a></li>
                </ul>
            </li>
            <li><a href="javascript:;">Sắp xếp theo giá</a>
                <ul class="dropdown-filter">
                    <li class="checked"><a href="">Tất cả</a></li>
                    <li><a href="/may-tinh-bang?order=thap-den-cao">Giá thấp đến cao</a></li>
                    <li><a href="/may-tinh-bang?order=cao-den-thap">Giá cao đến thấp</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="product-list">
        <div class="product-list-item">
            <div class="product-item-image">
                <div class="hot-and-new">
                </div>
                <a href="https://mobilecity.vn/may-tinh-bang/ipad-air-cu.html">
                    <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2016/11/ipad-mini-cu-3g-wifi-cu-xach-tay-quoc-te-gia-re-nhat-MobileCity-2-2-small.jpg" alt="ipad-mini-cu-3g-wifi-cu-xach-tay-quoc-te-gia-re-nhat-MobileCity-2-2" />
                </a>
                <div class="mask">
                    <a href="https://mobilecity.vn/may-tinh-bang/ipad-air-cu.html">
                        <div class="mask-title">
                            <div class="icon"></div>
                            <div class="text">MobileCity Care</div>
                        </div>
                        <ul class="mask-list">
                            <li>BH 6 tháng nguồn, màn hình</li>
                            <li>Đổi mới 15 ngày đầu tiên</li>
                            <li>Tặng tấm dán màn hình</li>
                            <li>Hỗ trợ phần mềm trọn đời máy</li>
                        </ul>
                    </a>
                    <a class="mask-link" target="_blank" title="Xem chi tiết chính sách bảo hành tại MobileCity" href="#">Bảo hành vàng</a>
                </div>
            </div>
            <div class="product-item-info">
                <div class="product-item-left">
                    <p class="name"><a href="https://mobilecity.vn/may-tinh-bang/ipad-air-cu.html">iPad Air Cũ (Air 1)</a></p>
                    <p class="price">5.550.000 ₫</p>
                </div>
                <div class="product-item-right">
                    <div class="all-icon icon-promotion"></div>
                    <a href="https://mobilecity.vn/may-tinh-bang/ipad-air-cu.html" class="buy">Mua</a>
                </div>
                <div class="product-item-full-width">
                    <ul>
                        <li><p>1. Tặng: <span style="color: #ff0000;">Cường lực -</span> <span style="color: #ff0000;">Ốp lưng - Tai nghe</span> khi mua BHV</p></li>
                        <li><p>2. Giảm: <span style="color: #ff0000;">100K</span> áp dụng HSSV mua BHV tại <span style="color: #ff0000;">398 Cầu Giấy</span></p></li>
                        <li><p>3. Mua: Dán cường lực 5D chỉ <span style="color: #ff0000;">99K</span></p></li>
                        <li><p>4. Giảm 100K khi mua BHV và đặt hàng tại: <a title="https://goo.gl/PH4Pw9" href="https://www.messenger.com/t/dienthoaixiaomigiare.vn">Đây</a></p></li>
                        <li><p>5. Cam kết bán iPhone RẺ nhất VN: <a title="iPhone giá RẺ" href="https://goo.gl/6xKTMo">CLICK</a></p></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="product-list-item">
            <div class="product-item-image">
                <div class="hot-and-new">
                </div>
                <a href="https://mobilecity.vn/may-tinh-bang/ipad-mini-3-cu.html">
                    <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2016/11/ipad-mini-3-3g-wifi-cu-xach-tay-quoc-te-gia-re-nhat-MobileCity-small.jpg" alt="ipad-mini-3-3g-wifi-cu-xach-tay-quoc-te-gia-re-nhat-MobileCity" />
                </a>
                <div class="mask">
                    <a href="https://mobilecity.vn/may-tinh-bang/ipad-mini-3-cu.html">
                        <div class="mask-title">
                            <div class="icon"></div>
                            <div class="text">MobileCity Care</div>
                        </div>
                        <ul class="mask-list">
                            <li>BH 6 tháng nguồn, màn hình</li>
                            <li>Đổi mới 15 ngày đầu tiên</li>
                            <li>Tặng tấm dán màn hình</li>
                            <li>Hỗ trợ phần mềm trọn đời máy</li>
                        </ul>
                    </a>
                    <a class="mask-link" target="_blank" title="Xem chi tiết chính sách bảo hành tại MobileCity" href="#">Bảo hành vàng</a>
                </div>
            </div>
            <div class="product-item-info">
                <div class="product-item-left">
                    <p class="name"><a href="https://mobilecity.vn/may-tinh-bang/ipad-mini-3-cu.html">iPad Mini 3 Cũ</a></p>
                    <p class="price">5.650.000 ₫</p>
                </div>
                <div class="product-item-right">
                    <div class="all-icon icon-promotion"></div>
                    <a href="https://mobilecity.vn/may-tinh-bang/ipad-mini-3-cu.html" class="buy">Mua</a>
                </div>
                <div class="product-item-full-width">
                    <ul>
                        <li><p>1. Tặng: <span style="color: #ff0000;">Cường lực -</span> <span style="color: #ff0000;">Ốp lưng - Tai nghe</span> khi mua BHV</p></li>
                        <li><p>2. Giảm: <span style="color: #ff0000;">100K</span> áp dụng HSSV mua BHV tại <span style="color: #ff0000;">398 Cầu Giấy</span></p></li>
                        <li><p>3. Mua: Dán cường lực 5D chỉ <span style="color: #ff0000;">99K</span></p></li>
                        <li><p>4. Giảm 100K khi mua BHV và đặt hàng tại: <a title="https://goo.gl/PH4Pw9" href="https://www.messenger.com/t/dienthoaixiaomigiare.vn">Đây</a></p></li>
                        <li><p>5. Cam kết bán iPhone RẺ nhất VN: <a title="iPhone giá RẺ" href="https://goo.gl/6xKTMo">CLICK</a></p></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="view-ajax-more">
        <img src="https://mobilecity.vn/public/assets/img/load_video.svg" alt="load_video">
    </div>
    <div class="viewmore">
        <a class="more" href="javascript:;" id="product_view_more" data-get_price="" data-get_os="" data-get_display="" data-get_feature="" data-get_order="" data-count="10">Xem thêm máy tính bảng</a>
    </div>
</section>
<div class="intro-category">
</div>