<?php $this->assets->outputCss('csspk'); ?>
<div class="breadcrumb">
    <ul itemscope itemtype="http://schema.org/BreadcrumbList">
        <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            <a itemprop="item" href="https://mobilecity.vn"><span itemprop="name">Trang chủ</span></a>
            <meta itemprop="position" content="1" />
        </li>
        <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            <a itemprop="item" href="https://mobilecity.vn/phu-kien"><span itemprop="name">Phụ kiện</span></a>
            <meta itemprop="position" content="2" />
        </li>
    </ul>
</div> <h1 class="intro-accessories-title">Phụ kiện điện thoại</h1>
<div class="intro-service-content css-content">
    <a href="javascript:;" class="intro_cate_more" style="display: none;">[ + xem thêm ]</a>
</div>
<section class="product-box">
    <div class="product-list">
        <div class="service-list-item">
            <div class="service-item-image">
                <a href="https://mobilecity.vn/phu-kien/akg-type--c.html">
                    <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2019/07/akg-type-c-small.jpg" alt="akg-type-c" style="">
                </a>
            </div>
                <div class="service-item-info">
                    <div class="service-item-left">
                        <p class="name"><a href="https://mobilecity.vn/phu-kien/akg-type--c.html" title="Tai nghe Samsung AKG Type-C">Tai nghe Samsung AKG Type-C</a></p>
                        <p class="price">Liên hệ</p>
                    </div>
                    <div class="service-item-right">
                        <a href="https://mobilecity.vn/phu-kien/akg-type--c.html" class="buy">Mua</a>
                    </div>
                </div>
        </div>
    </div>
    <div class="view-ajax-more">
        <img src="https://mobilecity.vn/public/assets/img/load_video.svg" alt="load_video">
    </div>
    <div class="viewmore">
        <a class="more" href="javascript:;">Xem thêm phụ kiện</a>
    </div>
</section>
<?php $this->assets->outputJs('jspk'); ?>