<?php $this->assets->outputCss('csstt'); ?>
<section class="container">
    <div class="breadcrumb">
        <ul itemscope itemtype="http://schema.org/BreadcrumbList">
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="https://mobilecity.vn"><span itemprop="name">Trang chủ</span></a>
                <meta itemprop="position" content="1" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="https://mobilecity.vn/tin-tuc"><span itemprop="name">Tin tức</span></a>
                <meta itemprop="position" content="2" />
            </li>
        </ul>
    </div> 
    <div class="categories">
        <p class="categories-title">Danh mục:</p>
        <ul class="categories-list">
            <li><a href="https://mobilecity.vn/tin-tuc-khuyen-mai">Tin khuyến mại</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc-tu-van-chon-mua">Tư vấn chọn mua</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc-goc-ky-thuat">Góc kỹ thuật</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc-tuyen-dung">Tuyển dụng</a></li>
        </ul>
    </div>
    <div class="news-content">
        <div class="news-content-list">
            <div class="news-content-item">
                <div class="img">
                    <a href="https://mobilecity.vn/tin-tuc/mang-6g-se-co-toc-do-truyen-tai-gap-8000-lan-mang-5g.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb1.jpg" alt="thumb1"></a>
                </div>
                <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/mang-6g-se-co-toc-do-truyen-tai-gap-8000-lan-mang-5g.html">Mạng 6G sẽ có tốc độ truyền tải gấp 8000 lần mạng 5G</a></h3>
                <div class="description"> Mặc dù mạng không dây 5G chưa phủ sóng đến nhiều quốc gia nhưng các nhà nghiên cứu tại Trung Quóc đã bắt đầu phát triển thế hệ mạng không dây tiếp theo.
                    
                Mới đây, bộ Khoa học và Công nghệ Trung Quốc đã bắt tay vào việc phát triển mạng không dây thế hệ tiếp theo (tạm gọi là 6G) và các ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/realme-x50-5g-chinh-thuc-ra-mat-man-hinh-120hz-snapdragon-765g-gia-tu-8-3-trieu-dong.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/01/thumb1.jpg" alt="thumb1"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/realme-x50-5g-chinh-thuc-ra-mat-man-hinh-120hz-snapdragon-765g-gia-tu-8-3-trieu-dong.html">Realme X50 5G chính thức ra mắt: Màn hình 120Hz, SnapDragon 765G giá từ 8.3 triệu đồng</a></h3>
            <div class="description"> Sau nhiều lần lộ diện dưới dạng tin đồn, hôm nay ngày 07/01/2019, chiếc Realme X50 5G chính thức được trình làng !
                
            Đây có lẽ là sản phẩm được sinh ra để cạnh tranh với Xiaomi Redmi K30 5G nên Realme X50 có khá nhiều điểm tương đồng với đối thủ. Từ màn hình, thiết kế, hiệu năng và cả ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/poco-x2-chinh-thuc-ra-mat-tai-thi-truong-an-do-man-hinh-120hz-gia-chi-5-2-trieu-dong.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb1-3-medium.jpg" alt="thumb1-3"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/poco-x2-chinh-thuc-ra-mat-tai-thi-truong-an-do-man-hinh-120hz-gia-chi-5-2-trieu-dong.html">POCO X2 chính thức ra mắt tại thị trường Ấn Độ, màn hình 120Hz giá chỉ 5.2 triệu đồng</a></h3>
            <p class="time">14:53 04/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> Hôm nay, Pocophone vừa cho ra mắt mẫu smartphone đầu tiên kể từ khi hãng tách riêng khỏi Xiaomi, chiếc điện thoại có tên Poco X2.
                
            Về bản chất, chếc Poco X2 là chiếc Redmi K30 4G được đổi tên tại thị trường quốc tế, có nghĩa Redmi K30 4G tại thị trường Trung Quốc sẽ được phân phối chính ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/meizu-17-lo-dien-voi-man-hinh-not-ruoi-vien-man-hinh-cuc-mong.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb1-2-medium.jpg" alt="thumb1-2"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/meizu-17-lo-dien-voi-man-hinh-not-ruoi-vien-man-hinh-cuc-mong.html">Meizu 17 lộ diện với màn hình nốt ruồi, viền màn hình cực mỏng</a></h3>
            <p class="time">15:48 03/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> Hôm nay, một hình ảnh rò rỉ được cho là của Meizu 17 bất ngờ được đăng tải trên internet, hé lộ nhiều thông tin thú vị về mẫu flagship tiếp theo đến từ Meizu.
                
                Trang tin Slashleaks đã bất ngờ chia sẻ hình ảnh mặt trước của chiếc Meizu 17 săp được ra mắt. Bức ảnh cho thấy, meizu sẽ sử ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/xperia-5-plus-lo-anh-concept-cuc-dep-khien-fan-ngay-ngat.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/xperia-5-plus-copy-medium.jpg" alt="xperia-5-plus-copy"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/xperia-5-plus-lo-anh-concept-cuc-dep-khien-fan-ngay-ngat.html">Xperia 5 Plus lộ ảnh concept cực đẹp, khiến fan ngây ngất</a></h3>
            <p class="time">14:53 03/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> Trong thời gian gần đây, nhiều tin đồn liên quan tới chiếc flagship tiếp theo của Sony có tên gọi Sony Xperia 5 Plus (hoặc Xperia 1.1) sẽ được trình làng trong sự kiện MWC sắp tới. Hôm nay, hình ảnh concept Xperia 5 Plus của Steve Hemmerstoffer hợp tác với Slashleaks bất ngờ được đăng tải trên ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/top-game-hay-nhat-cho-iphone-khong-the-bo-qua.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb-iphone-medium.jpg" alt="thumb-iphone"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/top-game-hay-nhat-cho-iphone-khong-the-bo-qua.html">TOP Game miễn phí, hay nhất cho iphone không thể bỏ qua !!!</a></h3>
            <p class="time">16:08 02/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> Tuy những  điện thoại Android không ngừng được nâng cấp về cấu hình nhưng trải nghiệm game trên máy Android vẫn thua xa  iphone  cùng đời hoặc thậm chí kém một đời. TOP Game miễn phí, hay nhất cho iphone đang HOT nhất 2019 được nhiều người chơi nhất thời điểm hiển tại. Cùng MobileCity điểm qua ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/nokia-captain-america-lo-cau-hinh-va-gia-ban-rat-co-the-la-nokia-5-2.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb5-2-medium.jpg" alt="thumb5-2"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/nokia-captain-america-lo-cau-hinh-va-gia-ban-rat-co-the-la-nokia-5-2.html">Nokia Captain America lộ cấu hình và giá bán, rất có thể là Nokia 5.2!</a></h3>
            <p class="time">15:40 02/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> Trong sự kiện MWC vào cuối tháng 2 sắp tới, Nokia sẽ giới thiệu hàng loạt mẫu điện thoại mới của mình. Theo những rò rỉ gần đây, chiếc Nokia có tên mã “Captain America” sẽ chính thức xuất hiện trong sự kiện nói trên.
                
            Mới đây, leaker nổi tiếng Evan Blass đã bất ngờ chia sẻ một vài hình ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/super-vooc-voi-cong-suat-80w-se-duoc-thuong-mai-hoa-trong-nam-nay.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb6-medium.jpg" alt="thumb6"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/super-vooc-voi-cong-suat-80w-se-duoc-thuong-mai-hoa-trong-nam-nay.html">Super VOOC với công suất 80W sẽ được thương mại hóa trong năm nay?</a></h3>
            <p class="time">14:34 02/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> Trong năm ngoái, OPPO đã tích hợp công nghệ Super VOOC với công suất sạc 65W trên chiếc OPPO Reno Ace và nhiều khả năng OPPO sẽ đẩy dòng sạc của công nghệ Super VOOC lên 80W trong năm nay.
                
            Tại Trung Quốc, một tài khoản có tên là Digital Chat Station đã tiết lộ một thông tin rất thú vị ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/lo-bang-sang-che-cua-xiaomi-mi-mix-fold--smartphone-man-hinh-gap-dau-tien-cua-xiaomi.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb4-1-medium.jpg" alt="thumb4-1"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/lo-bang-sang-che-cua-xiaomi-mi-mix-fold--smartphone-man-hinh-gap-dau-tien-cua-xiaomi.html">Lộ bằng sáng chế của Xiaomi Mi Mix Fold - Smartphone màn hình gập đầu tiên của Xiaomi</a></h3>
            <p class="time">17:27 01/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> Trong năm ngoái, nhiều tin đồn xoay quanh chiếc smartphone có màn hình gập đầu tiên của Xiaomi sẽ được trình làng trong thời gian sắp tới. Mới đây, một bằng sáng chế của Xiaomi đã được lộ diện, cho ta cái nhìn cận cảnh về thiết kế của chiếc điện thoại độc đáo này.
                
                
            Về tên ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/website-theo-doi-tinh-hinh-lay-lan-cua-dich-virus-corona.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb2-medium.jpg" alt="thumb2"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/website-theo-doi-tinh-hinh-lay-lan-cua-dich-virus-corona.html">Website theo dõi tình hình lây lan của dịch virus corona</a></h3>
            <p class="time">15:52 01/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> TTO - Virus corona chủng mới gây viêm đường hô hấp cấp (hay còn gọi là nCoV, virus corona Vũ Hán, bệnh viêm phổi Vũ Hán) đang hoành hành, khiến người mắc bệnh có các biểu hiện như ho, sốt và khó thở, suy yếu nội tạng...
            Chủng virus corona đang lây lan nhanh chóng trên thế giới và chưa có dấu ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/mang-6g-se-co-toc-do-truyen-tai-gap-8000-lan-mang-5g.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb1-medium.jpg" alt="thumb1"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/mang-6g-se-co-toc-do-truyen-tai-gap-8000-lan-mang-5g.html">Mạng 6G sẽ có tốc độ truyền tải gấp 8000 lần mạng 5G</a></h3>
            <p class="time">15:06 01/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> Mặc dù mạng không dây 5G chưa phủ sóng đến nhiều quốc gia nhưng các nhà nghiên cứu tại Trung Quóc đã bắt đầu phát triển thế hệ mạng không dây tiếp theo.
                
            Mới đây, bộ Khoa học và Công nghệ Trung Quốc đã bắt tay vào việc phát triển mạng không dây thế hệ tiếp theo (tạm gọi là 6G) và các ...</div>
            </div>
            <div class="news-content-item">
            <div class="img">
            <a href="https://mobilecity.vn/tin-tuc/iphone-9-co-the-bi-tri-hoan-do-corona.html"><img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/02/thumb-medium.jpg" alt="thumb"></a>
            </div>
            <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/iphone-9-co-the-bi-tri-hoan-do-corona.html">iPhone 9 có thể bị trì hoãn do virus corona!</a></h3>
            <p class="time">15:01 01/02/2020 - <a href="https://mobilecity.vn/tin-tuc-cong-nghe">Tin công nghệ</a></p>
            <div class="description"> Vào những ngày vừa qua, chủng Virus corona đã gây náo loạn toàn thế giới. Tại Trung Quốc, nhiều nhà máy, xí nghiệp đã phải đóng cửa để tránh lây lan dịch bệnh. Thật không may, hầu hết dây chuyền sản xuất các thết bị công nghệ tới từ hãng “Táo khuyết” đều được đặt ở đất nước tỷ dân này. Chính vì ...</div>
            </div>
            <div class="pagination-box">
            <ul class="pagination">
            <li class="disabled"><span>&laquo;</span></li>
            <li class="active"><span>1</span></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=2">2</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=3">3</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=4">4</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=5">5</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=6">6</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=7">7</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=8">8</a></li>
            <li class="disabled"><span>...</span></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=356">356</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=357">357</a></li>
            <li><a href="https://mobilecity.vn/tin-tuc?page=2" rel="next">&raquo;</a></li>
            </ul>
            </div> 
        </div>
        <div class="sidebar">
        <div class="product-sidebar">
        <div class="product-sidebar-title">Sản phẩm mới</div>
        <div class="product-sidebar-list">
        <div class="product-sidebar-item">
        <div class="img">
        <a href="https://mobilecity.vn/oppo/realme-x50.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/01/realme-x50-mc-glacier-tiny.jpg" alt="realme-x50-mc-glacier">
        </a>
        </div>
        <p class="name"><a href="https://mobilecity.vn/oppo/realme-x50.html">Realme X50 5G</a></p>
        <p class="price">8.250.000 ₫</p>
        </div>
        <div class="product-sidebar-item">
        <div class="img">
        <a href="https://mobilecity.vn/oppo/oppo-reno-3-pro.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/01/oppo-reno-3-pro-5g-do-tiny.jpg" alt="oppo-reno-3-pro-5g-do">
        </a>
        </div>
        <p class="name"><a href="https://mobilecity.vn/oppo/oppo-reno-3-pro.html">OPPO Reno 3 Pro 5G</a></p>
        <p class="price">12.450.000 ₫</p>
        </div>
        <div class="product-sidebar-item">
        <div class="img">
        <a href="https://mobilecity.vn/xiaomi/xiaomi-redmi-k30-5g.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2019/12/redmi-k30-4g-tim-tiny.jpg" alt="redmi-k30-4g-tim">
        </a>
        </div>
        <p class="name"><a href="https://mobilecity.vn/xiaomi/xiaomi-redmi-k30-5g.html">Xiaomi Redmi K30 5G</a></p>
        <p class="price">8.450.000 ₫</p>
        </div>
        <div class="product-sidebar-item">
        <div class="img">
        <a href="https://mobilecity.vn/vivo/vivo-s5.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2019/11/vivos5-tiny.jpg" alt="vivos5">
        </a>
        </div>
        <p class="name"><a href="https://mobilecity.vn/vivo/vivo-s5.html">Vivo S5</a></p>
        <p class="price">8.450.000 ₫</p>
        </div>
        <div class="product-sidebar-item">
        <div class="img">
        <a href="https://mobilecity.vn/xiaomi/xiaomi-redmi-k30.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2019/12/redmi-k30-5g-blue-tiny.jpg" alt="redmi-k30-5g-blue">
        </a>
        </div>
        <p class="name"><a href="https://mobilecity.vn/xiaomi/xiaomi-redmi-k30.html">Xiaomi Redmi K30 (RAM 6GB, 8GB)</a></p>
        <p class="price">5.350.000 ₫</p>
        </div>
        </div>
        </div>
        <div class="news-sidebar">
        <div class="news-sidebar-title">Khuyến mại</div>
        <div class="news-sidebar-list">
        <div class="news-sidebar-item">
        <div class="image">
        <a href="https://mobilecity.vn/tin-tuc/nhan-mien-phi-den-7gb-data-viettel-chi-bang-mot-buoc.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/01/viettel-free-4g-800x450-medium.jpg" alt="viettel-free-4g-800x450">
        </a>
        </div>
        <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/nhan-mien-phi-den-7gb-data-viettel-chi-bang-mot-buoc.html">Nhận miễn phí đến 7GB Data Viettel chỉ bằng một bước</a></h3>
        </div>
        <div class="news-sidebar-item">
        <div class="image">
        <a href="https://mobilecity.vn/tin-tuc/mobilecity--lich-nghi-tet-nguyen-dan-2020.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2020/01/tet-mobilecity-medium.jpg" alt="tet-mobilecity">
        </a>
        </div>
        <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/mobilecity--lich-nghi-tet-nguyen-dan-2020.html">MobileCity - lịch nghỉ tết Nguyên Đán 2020</a></h3>
        </div>
        <div class="news-sidebar-item">
        <div class="image">
        <a href="https://mobilecity.vn/tin-tuc/uyen-pu-tang-100-acc-lien-quan-mobile-cho-fan-cua-mobilecity.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2019/08/suwkien2-medium.jpg" alt="suwkien2">
        </a>
        </div>
        <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/uyen-pu-tang-100-acc-lien-quan-mobile-cho-fan-cua-mobilecity.html">Uyên Pu tặng 100 Acc Liên Quân Mobile cho Fan của MobileCity</a></h3>
        </div>
        <div class="news-sidebar-item">
        <div class="image">
        <a href="https://mobilecity.vn/tin-tuc/ve-sinh-tu-van-dich-vu-mien-phi-khong-sua-khong-sao.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2019/03/tu-van-mien-phi-medium.jpg" alt="tu-van-mien-phi">
        </a>
        </div>
        <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/ve-sinh-tu-van-dich-vu-mien-phi-khong-sua-khong-sao.html">Vệ sinh, tư vấn dịch vụ Miễn Phí - Không sửa không sao</a></h3>
        </div>
        <div class="news-sidebar-item">
        <div class="image">
        <a href="https://mobilecity.vn/tin-tuc/tang-voucher-giam-gia-dich-vu-50k-tai-tat-ca-chi-nhanh.html">
        <img class="lazy" src="https://mobilecity.vn/public/assets/img/load_video.svg" data-original="https://sudospaces.com/mobilecity-vn/images/2019/03/the-giftcard-medium.jpg" alt="the-giftcard">
        </a>
        </div>
        <h3 class="name"><a href="https://mobilecity.vn/tin-tuc/tang-voucher-giam-gia-dich-vu-50k-tai-tat-ca-chi-nhanh.html">Tặng Voucher giảm giá dịch vụ 50K tại tất cả chi nhánh</a></h3>
        </div>
        </div>
        </div>
        </div> 
    </div>
</section>
<?php $this->assets->outputJs('jstt'); ?>